name: Publish Book

on:
  push:
    branches:
      - main

env:
  BOOK_FOLDER: "book" # 电子书生成的文件夹名

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install Rust and mdBook
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install mdBook
        run: |
          mkdir mdbook
          curl -Lf https://github.com/rust-lang/mdBook/releases/download/v0.4.27/mdbook-v0.4.27-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=./mdbook
          echo `pwd`/mdbook >> $GITHUB_PATH
        env:
          CARGO_INSTALL_ROOT: /opt/hostedtoolcache/cargo
          PATH: ${{env.CARGO_INSTALL_ROOT}}/bin:${PATH}

      - name: Build Book
        run: mdbook build

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.github-action }}
          publish_dir: ./src/$BOOK_FOLDER/book
